branch-defaults:
  master:
    environment: Ipv6MappingApi-env
environment-defaults:
  Ipv6MappingApi-env:
    branch: master
    repository: origin
global:
  application_name: IPv6 Mapping Api
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.8.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
